png('plot4.png', width = 480, height = 480)
library(sqldf)
data <- read.csv.sql('household_power_consumption.txt',,sep = ';',sql = 'select * from file where Date in("1/2/2007","2/2/2007")',header = TRUE,
                     colClasses = c('character','character','character','character','character','character','character','character','character'))
Sys.setlocale('LC_TIME','C')
data$Date <- as.Date(data$Date, '%d/%m/%Y')
data$Time <- strptime(data$Time,'%H:%M:%S')
data$Time <- format(data$Time, '%H:%M:%S')
#generate var 'day' to identify weekdays
day <- paste(data$Date, data$Time)
dataall <- cbind(data,day)
dataall$day <- strptime(dataall$day, '%Y-%m-%d %H:%M:%S')
sub <- append(as.numeric(dataall$Sub_metering_1),as.numeric(dataall$Sub_metering_2))
sub <- append(sub,as.numeric(dataall$Sub_metering_3))
label <- append(rep('sub1',2880),rep('sub2',2880))
label <- append(label,rep('sub3',2880))
time <- rep(dataall$day,3)
energy <- data.frame(x = sub,y = label)
energy <- cbind(energy,time)

par(mfcol = c(2,2), mar = c(4,4,2,1))
with(dataall,plot(day,dataall$Global_active_power,ty = 'l',ylab = 'Global Active Power',xlab = ''))
with(energy,plot(time,x, type = 'n',xlab = '', ylab = 'Energy sub metering',yaxt = 'n'))
with(subset(energy,y == 'sub1'),lines(time,x, col = 'black'))
with(subset(energy,y == 'sub2'),lines(time,x, col = 'red'))
with(subset(energy,y == 'sub3'),lines(time,x, col = 'blue'))
axis(2,at = c(0,10,20,30),labels = c(0,10,20,30))
legend('topright',legend = c('Sub_metering_1','Sub_metering_2','Sub_metering_3'), lwd = 1, col = c('black','red','blue'),cex = 1,bty = 'n')
with(dataall,plot(day,dataall$Voltage,ty = 'l',ylab = 'Voltage',xlab = 'datetime'))
with(dataall,plot(day,dataall$Global_reactive_power,ty = 'l',ylab = 'Global_reactive_power',xlab = 'datetime'))
dev.off()